// AUTO-GENERATED by update_gallery.py — do not edit by hand.
window.NISARG_GALLERY = {
  "categories": [
    {
      "slug": "portrait",
      "label": "Portrait",
      "folder": "Portrait",
      "images": [
        {
          "src": "./Portrait/1.avif",
          "alt": "Portrait photography — 1"
        },
        {
          "src": "./Portrait/2.avif",
          "alt": "Portrait photography — 2"
        },
        {
          "src": "./Portrait/3.avif",
          "alt": "Portrait photography — 3"
        },
        {
          "src": "./Portrait/DSC03560_compressed.jpg",
          "alt": "Portrait photography — DSC03560 compressed"
        },
        {
          "src": "./Portrait/DSC03593_compressed.jpg",
          "alt": "Portrait photography — DSC03593 compressed"
        },
        {
          "src": "./Portrait/DSC03615_compressed.jpg",
          "alt": "Portrait photography — DSC03615 compressed"
        },
        {
          "src": "./Portrait/DSC03632_compressed.jpg",
          "alt": "Portrait photography — DSC03632 compressed"
        },
        {
          "src": "./Portrait/DSC03646_compressed.jpg",
          "alt": "Portrait photography — DSC03646 compressed"
        },
        {
          "src": "./Portrait/DSC03656_compressed.jpg",
          "alt": "Portrait photography — DSC03656 compressed"
        },
        {
          "src": "./Portrait/DSC03695_compressed.jpg",
          "alt": "Portrait photography — DSC03695 compressed"
        },
        {
          "src": "./Portrait/DSC03716_compressed.jpg",
          "alt": "Portrait photography — DSC03716 compressed"
        },
        {
          "src": "./Portrait/DSC03735_compressed.jpg",
          "alt": "Portrait photography — DSC03735 compressed"
        },
        {
          "src": "./Portrait/DSC03748_compressed.jpg",
          "alt": "Portrait photography — DSC03748 compressed"
        },
        {
          "src": "./Portrait/DSC03766_compressed.jpg",
          "alt": "Portrait photography — DSC03766 compressed"
        },
        {
          "src": "./Portrait/DSC03771_compressed.jpg",
          "alt": "Portrait photography — DSC03771 compressed"
        },
        {
          "src": "./Portrait/DSC03779.jpg",
          "alt": "Portrait photography — DSC03779"
        },
        {
          "src": "./Portrait/DSC03785.jpg",
          "alt": "Portrait photography — DSC03785"
        },
        {
          "src": "./Portrait/DSC03791.jpg",
          "alt": "Portrait photography — DSC03791"
        },
        {
          "src": "./Portrait/DSC03792.jpg",
          "alt": "Portrait photography — DSC03792"
        },
        {
          "src": "./Portrait/DSC03890.jpg",
          "alt": "Portrait photography — DSC03890"
        },
        {
          "src": "./Portrait/DSC06675.jpg",
          "alt": "Portrait photography — DSC06675"
        },
        {
          "src": "./Portrait/DSC06676.jpg",
          "alt": "Portrait photography — DSC06676"
        },
        {
          "src": "./Portrait/DSC06678.jpg",
          "alt": "Portrait photography — DSC06678"
        },
        {
          "src": "./Portrait/DSC06680.jpg",
          "alt": "Portrait photography — DSC06680"
        },
        {
          "src": "./Portrait/DSC06685.jpg",
          "alt": "Portrait photography — DSC06685"
        }
      ]
    },
    {
      "slug": "wedding",
      "label": "Wedding",
      "folder": "Weddings",
      "images": [
        {
          "src": "./Weddings/1.avif",
          "alt": "Wedding photography — 1"
        },
        {
          "src": "./Weddings/2.avif",
          "alt": "Wedding photography — 2"
        },
        {
          "src": "./Weddings/3.avif",
          "alt": "Wedding photography — 3"
        }
      ]
    },
    {
      "slug": "event",
      "label": "Event",
      "folder": "Event",
      "images": [
        {
          "src": "./Event/1.jpg",
          "alt": "Event photography — 1"
        },
        {
          "src": "./Event/2.jpg",
          "alt": "Event photography — 2"
        },
        {
          "src": "./Event/3.jpg",
          "alt": "Event photography — 3"
        },
        {
          "src": "./Event/DSC03005_compressed.jpg",
          "alt": "Event photography — DSC03005 compressed"
        },
        {
          "src": "./Event/DSC03056_compressed.jpg",
          "alt": "Event photography — DSC03056 compressed"
        },
        {
          "src": "./Event/DSC03154_compressed.jpg",
          "alt": "Event photography — DSC03154 compressed"
        },
        {
          "src": "./Event/DSC03345_compressed.jpg",
          "alt": "Event photography — DSC03345 compressed"
        },
        {
          "src": "./Event/DSC03358_compressed.jpg",
          "alt": "Event photography — DSC03358 compressed"
        },
        {
          "src": "./Event/DSC03482_compressed.jpg",
          "alt": "Event photography — DSC03482 compressed"
        },
        {
          "src": "./Event/DSC06009.jpg",
          "alt": "Event photography — DSC06009"
        },
        {
          "src": "./Event/DSC06249.jpg",
          "alt": "Event photography — DSC06249"
        },
        {
          "src": "./Event/DSC06326.jpg",
          "alt": "Event photography — DSC06326"
        },
        {
          "src": "./Event/DSC06872.jpg",
          "alt": "Event photography — DSC06872"
        },
        {
          "src": "./Event/DSC06877.jpg",
          "alt": "Event photography — DSC06877"
        },
        {
          "src": "./Event/DSC06881.jpg",
          "alt": "Event photography — DSC06881"
        },
        {
          "src": "./Event/DSC06945.jpg",
          "alt": "Event photography — DSC06945"
        },
        {
          "src": "./Event/DSC06968.jpg",
          "alt": "Event photography — DSC06968"
        },
        {
          "src": "./Event/DSC06975.jpg",
          "alt": "Event photography — DSC06975"
        },
        {
          "src": "./Event/DSC07100%281%29.jpg",
          "alt": "Event photography — DSC07100(1)"
        },
        {
          "src": "./Event/DSC07116%281%29.jpg",
          "alt": "Event photography — DSC07116(1)"
        },
        {
          "src": "./Event/DSC07664%281%29.jpg",
          "alt": "Event photography — DSC07664(1)"
        },
        {
          "src": "./Event/DSC07761%281%29.jpg",
          "alt": "Event photography — DSC07761(1)"
        },
        {
          "src": "./Event/DSC07796%281%29.jpg",
          "alt": "Event photography — DSC07796(1)"
        }
      ]
    },
    {
      "slug": "birthday",
      "label": "Birthday",
      "folder": "Birthday",
      "images": [
        {
          "src": "./Birthday/1.jpg",
          "alt": "Birthday photography — 1"
        },
        {
          "src": "./Birthday/2.jpg",
          "alt": "Birthday photography — 2"
        },
        {
          "src": "./Birthday/3.jpg",
          "alt": "Birthday photography — 3"
        }
      ]
    },
    {
      "slug": "baby-shower",
      "label": "Baby Shower",
      "folder": "Baby",
      "images": [
        {
          "src": "./Baby/1.jpg",
          "alt": "Baby Shower photography — 1"
        },
        {
          "src": "./Baby/2.jpg",
          "alt": "Baby Shower photography — 2"
        },
        {
          "src": "./Baby/3.jpg",
          "alt": "Baby Shower photography — 3"
        },
        {
          "src": "./Baby/4.avif",
          "alt": "Baby Shower photography — 4"
        },
        {
          "src": "./Baby/DSC04689.jpg",
          "alt": "Baby Shower photography — DSC04689"
        },
        {
          "src": "./Baby/DSC04708.jpg",
          "alt": "Baby Shower photography — DSC04708"
        },
        {
          "src": "./Baby/DSC04738.jpg",
          "alt": "Baby Shower photography — DSC04738"
        },
        {
          "src": "./Baby/DSC04798.jpg",
          "alt": "Baby Shower photography — DSC04798"
        },
        {
          "src": "./Baby/DSC04809.jpg",
          "alt": "Baby Shower photography — DSC04809"
        },
        {
          "src": "./Baby/DSC04814.jpg",
          "alt": "Baby Shower photography — DSC04814"
        }
      ]
    }
  ],
  "total": 64
};
