#!/usr/bin/env python3
"""Build gallery-data.js from the photography category folders.

Usage:
    python update_gallery.py

Add/remove photos inside the configured folders, run this script, then upload/push
only the changed files. No portfolio.html editing is required.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif'}

# folder, filter slug, label
CATEGORIES = [
    ('Portrait', 'portrait', 'Portrait'),
    ('Weddings', 'wedding', 'Wedding'),
    ('Event', 'event', 'Event'),
    ('Birthday', 'birthday', 'Birthday'),
    ('Baby', 'baby-shower', 'Baby Shower'),
]


def natural_key(name: str):
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r'(\d+)', name)]


def web_path(folder: str, filename: str) -> str:
    return './' + quote(folder) + '/' + quote(filename)


def build_gallery():
    categories = []
    total = 0

    for folder, slug, label in CATEGORIES:
        category_dir = ROOT / folder
        if not category_dir.exists():
            continue

        images = sorted(
            [p for p in category_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS],
            key=lambda p: natural_key(p.name),
        )
        if not images:
            continue

        entries = []
        for image in images:
            entries.append({
                'src': web_path(folder, image.name),
                'alt': f'{label} photography — {image.stem.replace("_", " ").replace("-", " ")}',
            })

        categories.append({
            'slug': slug,
            'label': label,
            'folder': folder,
            'images': entries,
        })
        total += len(entries)

    return {'categories': categories, 'total': total}


def main():
    data = build_gallery()
    out = ROOT / 'gallery-data.js'
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    out.write_text(
        '// AUTO-GENERATED by update_gallery.py — do not edit by hand.\n'
        f'window.NISARG_GALLERY = {payload};\n',
        encoding='utf-8',
    )
    print(f'Gallery updated: {data["total"]} images across {len(data["categories"])} categories.')
    print(f'Created: {out.name}')


if __name__ == '__main__':
    main()
